using System;

namespace PlexDL.Player
{
    [Flags]
    internal enum GETPROPERTYSTOREFLAGS
    {
        GPS_DEFAULT,
        GPS_HANDLERPROPERTIESONLY,
        GPS_READWRITE,
        GPS_TEMPORARY,
        GPS_FASTPROPERTIESONLY,
        GPS_OPENSLOWITEM,
        GPS_DELAYCREATION,
        GPS_BESTEFFORT,
        GPS_NO_OPLOCK,
        GPS_PREFERQUERYPROPERTIES,
        GPS_EXTRINSICPROPERTIES,
        GPS_EXTRINSICPROPERTIESONLY,
        GPS_VOLATILEPROPERTIES,
        GPS_VOLATILEPROPERTIESONLY,
        GPS_MASK_VALID
    };
}