using System;
using System.IO;
using System.Linq;
using System.Reflection;

namespace PlexDL.Internal
{
    /// <summary>
    /// Handler for finding missing assemblies and reloading them on failure
    /// </summary>
    public static class AssemblyResolve
    {
        //THESE ARE THE FORMAL LOCATIONS OF PLEXDL FILES.
        //THEY ARE CREATED/REMOVED/UPDATED VIA POST-BUILD EVENTS.
        //DO NOT MODIFY UNLESS YOU ARE MODIFYING THE POST-BUILD EVENTS SCRIPT.
        public static string LibraryDirectory { get; } = @"lib";

        public static string DebugDirectory { get; } = @"pdb";
        public static string XmlDirectory { get; } = @""; //NOTE: These are generated by the compiler; not by PlexDL.

        /// <summary>
        /// Main locator and resolver
        /// <br></br>CREDIT: https://weblog.west-wind.com/posts/2016/dec/12/loading-net-assemblies-out-of-seperate-folders
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="args"></param>
        /// <returns></returns>
        public static Assembly HandleResolve(object sender, ResolveEventArgs args)
        {
            // Ignore missing resources
            if (args.Name.Contains(".resources"))
                return null;

            // check for assemblies already loaded
            var assembly = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.FullName == args.Name);
            if (assembly != null)
                return assembly;

            // Try to load by filename - split out the filename of the full assembly name
            // and append the base path of the original assembly (ie. look in the same dir)
            var filename = args.Name.Split(',')[0] + ".dll".ToLower();

            // Did the user specify a custom search directory? We need to try and fetch it.
            var customDir = DifferentAssemblyPath();

            // Top-most directory to search for libraries
            var searchDir = string.IsNullOrEmpty(customDir) ? Directory.GetCurrentDirectory() : customDir;

            try
            {
                return Directory.GetFiles(searchDir, filename, SearchOption.AllDirectories).Select(Assembly.LoadFrom).FirstOrDefault();
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// If the user wants to locate assemblies elsewhere, the below routine is executed when the correct argument is passed.
        /// </summary>
        /// <returns></returns>
        public static string DifferentAssemblyPath()
        {
            try
            {
                const string checkFor = @"-libDir=";
                var sep = checkFor[checkFor.Length - 1];

                foreach (var s in Program.Args)
                {
                    if (!s.Contains(checkFor)) continue;

                    var split = s.Split(sep);
                    if (split.Length != 2) continue;

                    var path = split[1];
                    if (Directory.Exists(path))
                        return path;
                }

                return string.Empty;
            }
            catch (Exception)
            {
                return string.Empty;
            }
        }
    }
}