//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace PlexDL.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("PlexDL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_backup_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_backup_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_backup_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_backup_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_backup_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_backup_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_backup_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_backup_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_book_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_book_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_book_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_book_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_book_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_book_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_book_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_book_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_cancel_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_cancel_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_cancel_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_cancel_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_cancel_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_cancel_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_cancel_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_cancel_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_cloud_download_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_cloud_download_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_cloud_download_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_cloud_download_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_cloud_download_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_cloud_download_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_cloud_download_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_cloud_download_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_directions_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_directions_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_directions_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_directions_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_directions_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_directions_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_directions_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_directions_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_dvr_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_dvr_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_dvr_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_dvr_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_dvr_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_dvr_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_dvr_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_dvr_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_fast_forward_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_fast_forward_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_fast_forward_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_fast_forward_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_fast_forward_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_fast_forward_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_fast_forward_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_fast_forward_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_fast_rewind_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_fast_rewind_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_fast_rewind_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_fast_rewind_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_fast_rewind_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_fast_rewind_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_fast_rewind_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_fast_rewind_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_folder_open_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_folder_open_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_folder_open_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_folder_open_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_folder_open_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_folder_open_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_folder_open_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_folder_open_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_pause_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_pause_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_pause_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_pause_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_pause_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_pause_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_pause_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_pause_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_play_arrow_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_play_arrow_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_play_arrow_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_play_arrow_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_play_arrow_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_play_arrow_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_play_arrow_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_play_arrow_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_power_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_power_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_power_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_power_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_power_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_power_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_power_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_power_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_power_off_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_power_off_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_power_off_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_power_off_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_power_off_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_power_off_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_power_off_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_power_off_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_refresh_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_refresh_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_refresh_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_refresh_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_refresh_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_refresh_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_refresh_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_refresh_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_rss_feed_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_rss_feed_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_rss_feed_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_rss_feed_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_rss_feed_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_rss_feed_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_rss_feed_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_rss_feed_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_save_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_save_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_save_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_save_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_save_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_save_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_save_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_save_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_search_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_search_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_search_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_search_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_search_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_search_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_search_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_search_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_settings_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_settings_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_settings_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_settings_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_settings_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_settings_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_settings_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_settings_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_signal_wifi_4_bar_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_signal_wifi_4_bar_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_signal_wifi_4_bar_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_signal_wifi_4_bar_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_signal_wifi_4_bar_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_signal_wifi_4_bar_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_signal_wifi_4_bar_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_signal_wifi_4_bar_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_signal_wifi_off_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_signal_wifi_off_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_signal_wifi_off_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_signal_wifi_off_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_signal_wifi_off_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_signal_wifi_off_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_signal_wifi_off_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_signal_wifi_off_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_skip_next_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_skip_next_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_skip_next_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_skip_next_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_skip_next_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_skip_next_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_skip_next_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_skip_next_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_skip_previous_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_skip_previous_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_skip_previous_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_skip_previous_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_skip_previous_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_skip_previous_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_skip_previous_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_skip_previous_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_stop_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_stop_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_stop_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_stop_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_stop_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_stop_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_stop_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_stop_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_video_library_black_18dp {
            get {
                object obj = ResourceManager.GetObject("baseline_video_library_black_18dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_video_library_black_18dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_video_library_black_18dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_video_library_black_48dp {
            get {
                object obj = ResourceManager.GetObject("baseline_video_library_black_48dp", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap baseline_video_library_black_48dp_white {
            get {
                object obj = ResourceManager.GetObject("baseline_video_library_black_48dp_white", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap image_not_available_png_8 {
            get {
                object obj = ResourceManager.GetObject("image_not_available_png_8", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string keywordBlacklist {
            get {
                return ResourceManager.GetString("keywordBlacklist", resourceCulture);
            }
        }
    }
}
